import sys; sys.argv = ['app']
import app
from sqlmodel import Session, text
from app import engine
C = 13
sqls = ["DELETE FROM businessdealnote WHERE deal_id IN (SELECT id FROM businessdeal WHERE client_id = %d)","DELETE FROM taskworksession WHERE task_id IN (SELECT id FROM task WHERE client_id = %d)","DELETE FROM worktimeentry WHERE project_id IN (SELECT id FROM workproject WHERE client_id = %d)","DELETE FROM workallocation WHERE project_id IN (SELECT id FROM workproject WHERE client_id = %d)","DELETE FROM workemployee WHERE project_id IN (SELECT id FROM workproject WHERE client_id = %d)","DELETE FROM businessdeal WHERE client_id = %d","DELETE FROM task WHERE client_id = %d","DELETE FROM workproject WHERE client_id = %d","DELETE FROM appnotification WHERE client_id = %d","DELETE FROM attachment WHERE client_id = %d","DELETE FROM clientbusinessprofile WHERE client_id = %d","DELETE FROM clientfinancebankaccount WHERE client_id = %d","DELETE FROM clientfinancecategory WHERE client_id = %d","DELETE FROM clientfinancecostcenter WHERE client_id = %d","DELETE FROM clientfinancerevenuetype WHERE client_id = %d","DELETE FROM clientfinancesupplier WHERE client_id = %d","DELETE FROM clientfinancialentry WHERE client_id = %d","DELETE FROM clientgroupcompany WHERE client_id = %d","DELETE FROM clientsnapshot WHERE client_id = %d","DELETE FROM clienttoolsubscription WHERE client_id = %d","DELETE FROM consultingproject WHERE client_id = %d","DELETE FROM contaazulinvoice WHERE client_id = %d","DELETE FROM contaazulpersonmap WHERE client_id = %d","DELETE FROM contaazulreceivable WHERE client_id = %d","DELETE FROM conversation WHERE client_id = %d","DELETE FROM creditconsent WHERE client_id = %d","DELETE FROM creditledger WHERE client_id = %d","DELETE FROM creditreport WHERE client_id = %d","DELETE FROM creditwallet WHERE client_id = %d","DELETE FROM document WHERE client_id = %d","DELETE FROM educationcourseaccess WHERE client_id = %d","DELETE FROM educationlessonprogress WHERE client_id = %d","DELETE FROM financeinvoice WHERE client_id = %d","DELETE FROM loansimulation WHERE client_id = %d","DELETE FROM meeting WHERE client_id = %d","DELETE FROM membership WHERE client_id = %d","DELETE FROM membershipclienttoolaccess WHERE client_id = %d","DELETE FROM notification WHERE client_id = %d","DELETE FROM offermatch WHERE client_id = %d","DELETE FROM offervisibilityreview WHERE client_id = %d","DELETE FROM officefinancialentry WHERE client_id = %d","DELETE FROM officefinancialrecurrence WHERE client_id = %d","DELETE FROM pendingitem WHERE client_id = %d","DELETE FROM proposal WHERE client_id = %d","DELETE FROM queryrun WHERE client_id = %d","DELETE FROM smartalert WHERE client_id = %d","DELETE FROM useractivity WHERE client_id = %d","DELETE FROM whatsappthread WHERE client_id = %d","DELETE FROM client WHERE id = %d"]
with Session(engine) as db:
    for sql in sqls:
        try: db.exec(text(sql % C))
        except Exception as e: print(f"SKIP: {e}")
    db.commit()
    print("OK - cliente 13 removido")
