"""crm negocios

Revision ID: 1ddf509a168c
Revises: b7f5b5db71d6
Create Date: 2026-03-12 15:02:40.287967

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = '1ddf509a168c'
down_revision: Union[str, Sequence[str], None] = 'b7f5b5db71d6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('businessdeal',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.Column('created_by_user_id', sa.Integer(), nullable=False),
    sa.Column('owner_user_id', sa.Integer(), nullable=True),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('demand', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('notes', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('stage', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('service_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('value_estimate_brl', sa.Float(), nullable=False),
    sa.Column('probability_pct', sa.Integer(), nullable=False),
    sa.Column('next_step', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('next_step_date', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('source', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('proposal_id', sa.Integer(), nullable=True),
    sa.Column('consulting_project_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['client.id'], ),
    sa.ForeignKeyConstraint(['company_id'], ['company.id'], ),
    sa.ForeignKeyConstraint(['consulting_project_id'], ['consultingproject.id'], ),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['owner_user_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['proposal_id'], ['proposal.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_businessdeal_client_id'), 'businessdeal', ['client_id'], unique=False)
    op.create_index(op.f('ix_businessdeal_company_id'), 'businessdeal', ['company_id'], unique=False)
    op.create_index(op.f('ix_businessdeal_consulting_project_id'), 'businessdeal', ['consulting_project_id'], unique=False)
    op.create_index(op.f('ix_businessdeal_created_by_user_id'), 'businessdeal', ['created_by_user_id'], unique=False)
    op.create_index(op.f('ix_businessdeal_owner_user_id'), 'businessdeal', ['owner_user_id'], unique=False)
    op.create_index(op.f('ix_businessdeal_proposal_id'), 'businessdeal', ['proposal_id'], unique=False)
    op.create_index(op.f('ix_businessdeal_service_name'), 'businessdeal', ['service_name'], unique=False)
    op.create_index(op.f('ix_businessdeal_stage'), 'businessdeal', ['stage'], unique=False)
    op.create_table('businessdealnote',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('deal_id', sa.Integer(), nullable=False),
    sa.Column('author_user_id', sa.Integer(), nullable=False),
    sa.Column('message', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['author_user_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['deal_id'], ['businessdeal.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_businessdealnote_author_user_id'), 'businessdealnote', ['author_user_id'], unique=False)
    op.create_index(op.f('ix_businessdealnote_deal_id'), 'businessdealnote', ['deal_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_businessdealnote_deal_id'), table_name='businessdealnote')
    op.drop_index(op.f('ix_businessdealnote_author_user_id'), table_name='businessdealnote')
    op.drop_table('businessdealnote')
    op.drop_index(op.f('ix_businessdeal_stage'), table_name='businessdeal')
    op.drop_index(op.f('ix_businessdeal_service_name'), table_name='businessdeal')
    op.drop_index(op.f('ix_businessdeal_proposal_id'), table_name='businessdeal')
    op.drop_index(op.f('ix_businessdeal_owner_user_id'), table_name='businessdeal')
    op.drop_index(op.f('ix_businessdeal_created_by_user_id'), table_name='businessdeal')
    op.drop_index(op.f('ix_businessdeal_consulting_project_id'), table_name='businessdeal')
    op.drop_index(op.f('ix_businessdeal_company_id'), table_name='businessdeal')
    op.drop_index(op.f('ix_businessdeal_client_id'), table_name='businessdeal')
    op.drop_table('businessdeal')
    # ### end Alembic commands ###
