"""reunioes notion

Revision ID: 228b71dc3151
Revises: 1ddf509a168c
Create Date: 2026-03-12 16:26:01.870185

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = '228b71dc3151'
down_revision: Union[str, Sequence[str], None] = '1ddf509a168c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('meeting',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.Column('created_by_user_id', sa.Integer(), nullable=False),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('meeting_date', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('source', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('notion_page_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('notion_url', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('notion_meeting_block_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('notion_status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('summary_text', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('notes_text', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('transcript_text', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('action_items_text', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('raw_json', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('last_synced_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['client.id'], ),
    sa.ForeignKeyConstraint(['company_id'], ['company.id'], ),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_meeting_client_id'), 'meeting', ['client_id'], unique=False)
    op.create_index(op.f('ix_meeting_company_id'), 'meeting', ['company_id'], unique=False)
    op.create_index(op.f('ix_meeting_created_by_user_id'), 'meeting', ['created_by_user_id'], unique=False)
    op.create_index(op.f('ix_meeting_notion_meeting_block_id'), 'meeting', ['notion_meeting_block_id'], unique=False)
    op.create_index(op.f('ix_meeting_notion_page_id'), 'meeting', ['notion_page_id'], unique=False)
    op.create_index(op.f('ix_meeting_notion_status'), 'meeting', ['notion_status'], unique=False)
    op.create_index(op.f('ix_meeting_source'), 'meeting', ['source'], unique=False)
    op.create_table('meetingmessage',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('meeting_id', sa.Integer(), nullable=False),
    sa.Column('author_user_id', sa.Integer(), nullable=False),
    sa.Column('message', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['author_user_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['meeting_id'], ['meeting.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_meetingmessage_author_user_id'), 'meetingmessage', ['author_user_id'], unique=False)
    op.create_index(op.f('ix_meetingmessage_meeting_id'), 'meetingmessage', ['meeting_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_meetingmessage_meeting_id'), table_name='meetingmessage')
    op.drop_index(op.f('ix_meetingmessage_author_user_id'), table_name='meetingmessage')
    op.drop_table('meetingmessage')
    op.drop_index(op.f('ix_meeting_source'), table_name='meeting')
    op.drop_index(op.f('ix_meeting_notion_status'), table_name='meeting')
    op.drop_index(op.f('ix_meeting_notion_page_id'), table_name='meeting')
    op.drop_index(op.f('ix_meeting_notion_meeting_block_id'), table_name='meeting')
    op.drop_index(op.f('ix_meeting_created_by_user_id'), table_name='meeting')
    op.drop_index(op.f('ix_meeting_company_id'), table_name='meeting')
    op.drop_index(op.f('ix_meeting_client_id'), table_name='meeting')
    op.drop_table('meeting')
    # ### end Alembic commands ###
