"""educacao sprint1

Revision ID: 29fcb784d782
Revises: 228b71dc3151
Create Date: 2026-03-12 17:25:54.966429

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = '29fcb784d782'
down_revision: Union[str, Sequence[str], None] = '228b71dc3151'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('educationcourse',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('created_by_user_id', sa.Integer(), nullable=False),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('category', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['company.id'], ),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('company_id', 'title', name='uq_education_course_company_title')
    )
    op.create_index(op.f('ix_educationcourse_company_id'), 'educationcourse', ['company_id'], unique=False)
    op.create_index(op.f('ix_educationcourse_created_by_user_id'), 'educationcourse', ['created_by_user_id'], unique=False)
    op.create_index(op.f('ix_educationcourse_is_active'), 'educationcourse', ['is_active'], unique=False)
    op.create_table('educationcourseaccess',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('course_id', sa.Integer(), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['client.id'], ),
    sa.ForeignKeyConstraint(['company_id'], ['company.id'], ),
    sa.ForeignKeyConstraint(['course_id'], ['educationcourse.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('course_id', 'client_id', name='uq_education_course_client')
    )
    op.create_index(op.f('ix_educationcourseaccess_client_id'), 'educationcourseaccess', ['client_id'], unique=False)
    op.create_index(op.f('ix_educationcourseaccess_company_id'), 'educationcourseaccess', ['company_id'], unique=False)
    op.create_index(op.f('ix_educationcourseaccess_course_id'), 'educationcourseaccess', ['course_id'], unique=False)
    op.create_table('educationmodule',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('course_id', sa.Integer(), nullable=False),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('order', sa.Integer(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['course_id'], ['educationcourse.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('course_id', 'order', name='uq_education_module_order')
    )
    op.create_index(op.f('ix_educationmodule_course_id'), 'educationmodule', ['course_id'], unique=False)
    op.create_index(op.f('ix_educationmodule_order'), 'educationmodule', ['order'], unique=False)
    op.create_table('educationlesson',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('module_id', sa.Integer(), nullable=False),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('order', sa.Integer(), nullable=False),
    sa.Column('video_url', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['module_id'], ['educationmodule.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('module_id', 'order', name='uq_education_lesson_order')
    )
    op.create_index(op.f('ix_educationlesson_module_id'), 'educationlesson', ['module_id'], unique=False)
    op.create_index(op.f('ix_educationlesson_order'), 'educationlesson', ['order'], unique=False)
    op.create_table('educationlessonprogress',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.Column('lesson_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('completed', sa.Boolean(), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['client.id'], ),
    sa.ForeignKeyConstraint(['company_id'], ['company.id'], ),
    sa.ForeignKeyConstraint(['lesson_id'], ['educationlesson.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('lesson_id', 'user_id', name='uq_education_lesson_user')
    )
    op.create_index(op.f('ix_educationlessonprogress_client_id'), 'educationlessonprogress', ['client_id'], unique=False)
    op.create_index(op.f('ix_educationlessonprogress_company_id'), 'educationlessonprogress', ['company_id'], unique=False)
    op.create_index(op.f('ix_educationlessonprogress_completed'), 'educationlessonprogress', ['completed'], unique=False)
    op.create_index(op.f('ix_educationlessonprogress_lesson_id'), 'educationlessonprogress', ['lesson_id'], unique=False)
    op.create_index(op.f('ix_educationlessonprogress_user_id'), 'educationlessonprogress', ['user_id'], unique=False)
    op.add_column('attachment', sa.Column('education_lesson_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_attachment_education_lesson_id'), 'attachment', ['education_lesson_id'], unique=False)
    op.create_foreign_key(None, 'attachment', 'educationlesson', ['education_lesson_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'attachment', type_='foreignkey')
    op.drop_index(op.f('ix_attachment_education_lesson_id'), table_name='attachment')
    op.drop_column('attachment', 'education_lesson_id')
    op.drop_index(op.f('ix_educationlessonprogress_user_id'), table_name='educationlessonprogress')
    op.drop_index(op.f('ix_educationlessonprogress_lesson_id'), table_name='educationlessonprogress')
    op.drop_index(op.f('ix_educationlessonprogress_completed'), table_name='educationlessonprogress')
    op.drop_index(op.f('ix_educationlessonprogress_company_id'), table_name='educationlessonprogress')
    op.drop_index(op.f('ix_educationlessonprogress_client_id'), table_name='educationlessonprogress')
    op.drop_table('educationlessonprogress')
    op.drop_index(op.f('ix_educationlesson_order'), table_name='educationlesson')
    op.drop_index(op.f('ix_educationlesson_module_id'), table_name='educationlesson')
    op.drop_table('educationlesson')
    op.drop_index(op.f('ix_educationmodule_order'), table_name='educationmodule')
    op.drop_index(op.f('ix_educationmodule_course_id'), table_name='educationmodule')
    op.drop_table('educationmodule')
    op.drop_index(op.f('ix_educationcourseaccess_course_id'), table_name='educationcourseaccess')
    op.drop_index(op.f('ix_educationcourseaccess_company_id'), table_name='educationcourseaccess')
    op.drop_index(op.f('ix_educationcourseaccess_client_id'), table_name='educationcourseaccess')
    op.drop_table('educationcourseaccess')
    op.drop_index(op.f('ix_educationcourse_is_active'), table_name='educationcourse')
    op.drop_index(op.f('ix_educationcourse_created_by_user_id'), table_name='educationcourse')
    op.drop_index(op.f('ix_educationcourse_company_id'), table_name='educationcourse')
    op.drop_table('educationcourse')
    # ### end Alembic commands ###
