"""consultoria projetos

Revision ID: 9bfc4a077534
Revises: 70087c783fac
Create Date: 2026-03-11 12:50:32.071571

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9bfc4a077534'
down_revision: Union[str, Sequence[str], None] = '70087c783fac'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('consultingproject',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.Column('created_by_user_id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('start_date', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('due_date', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['client.id'], ),
    sa.ForeignKeyConstraint(['company_id'], ['company.id'], ),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_consultingproject_client_id'), 'consultingproject', ['client_id'], unique=False)
    op.create_index(op.f('ix_consultingproject_company_id'), 'consultingproject', ['company_id'], unique=False)
    op.create_index(op.f('ix_consultingproject_created_by_user_id'), 'consultingproject', ['created_by_user_id'], unique=False)
    op.create_index(op.f('ix_consultingproject_status'), 'consultingproject', ['status'], unique=False)
    op.create_table('consultingstage',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('order', sa.Integer(), nullable=False),
    sa.Column('due_date', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['consultingproject.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_consultingstage_order'), 'consultingstage', ['order'], unique=False)
    op.create_index(op.f('ix_consultingstage_project_id'), 'consultingstage', ['project_id'], unique=False)
    op.create_table('consultingstep',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('stage_id', sa.Integer(), nullable=False),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('due_date', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('weight', sa.Float(), nullable=False),
    sa.Column('done', sa.Boolean(), nullable=False),
    sa.Column('client_action', sa.Boolean(), nullable=False),
    sa.Column('done_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['stage_id'], ['consultingstage.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_consultingstep_client_action'), 'consultingstep', ['client_action'], unique=False)
    op.create_index(op.f('ix_consultingstep_done'), 'consultingstep', ['done'], unique=False)
    op.create_index(op.f('ix_consultingstep_stage_id'), 'consultingstep', ['stage_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_consultingstep_stage_id'), table_name='consultingstep')
    op.drop_index(op.f('ix_consultingstep_done'), table_name='consultingstep')
    op.drop_index(op.f('ix_consultingstep_client_action'), table_name='consultingstep')
    op.drop_table('consultingstep')
    op.drop_index(op.f('ix_consultingstage_project_id'), table_name='consultingstage')
    op.drop_index(op.f('ix_consultingstage_order'), table_name='consultingstage')
    op.drop_table('consultingstage')
    op.drop_index(op.f('ix_consultingproject_status'), table_name='consultingproject')
    op.drop_index(op.f('ix_consultingproject_created_by_user_id'), table_name='consultingproject')
    op.drop_index(op.f('ix_consultingproject_company_id'), table_name='consultingproject')
    op.drop_index(op.f('ix_consultingproject_client_id'), table_name='consultingproject')
    op.drop_table('consultingproject')
    # ### end Alembic commands ###
