"""perfil snapshots

Revision ID: b7f5b5db71d6
Revises: d7356437b609
Create Date: 2026-03-12 14:41:21.475258

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'b7f5b5db71d6'
down_revision: Union[str, Sequence[str], None] = 'd7356437b609'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('clientsnapshot',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.Column('created_by_user_id', sa.Integer(), nullable=False),
    sa.Column('revenue_monthly_brl', sa.Float(), nullable=False),
    sa.Column('debt_total_brl', sa.Float(), nullable=False),
    sa.Column('cash_balance_brl', sa.Float(), nullable=False),
    sa.Column('employees_count', sa.Integer(), nullable=False),
    sa.Column('nps_score', sa.Integer(), nullable=False),
    sa.Column('notes', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('answers_json', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('score_process', sa.Float(), nullable=False),
    sa.Column('score_financial', sa.Float(), nullable=False),
    sa.Column('score_total', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['client.id'], ),
    sa.ForeignKeyConstraint(['company_id'], ['company.id'], ),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_clientsnapshot_client_id'), 'clientsnapshot', ['client_id'], unique=False)
    op.create_index(op.f('ix_clientsnapshot_company_id'), 'clientsnapshot', ['company_id'], unique=False)
    op.create_index(op.f('ix_clientsnapshot_created_by_user_id'), 'clientsnapshot', ['created_by_user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_clientsnapshot_created_by_user_id'), table_name='clientsnapshot')
    op.drop_index(op.f('ix_clientsnapshot_company_id'), table_name='clientsnapshot')
    op.drop_index(op.f('ix_clientsnapshot_client_id'), table_name='clientsnapshot')
    op.drop_table('clientsnapshot')
    # ### end Alembic commands ###
