"""credito scr lgpd

Revision ID: d4c25144d483
Revises: 29fcb784d782
Create Date: 2026-03-13 20:08:41.394264

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = 'd4c25144d483'
down_revision: Union[str, Sequence[str], None] = '29fcb784d782'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('creditconsent',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.Column('created_by_user_id', sa.Integer(), nullable=False),
    sa.Column('kind', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('signed_by_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('signed_by_document', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('signed_at', sa.DateTime(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('notes', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['client.id'], ),
    sa.ForeignKeyConstraint(['company_id'], ['company.id'], ),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_creditconsent_client_id'), 'creditconsent', ['client_id'], unique=False)
    op.create_index(op.f('ix_creditconsent_company_id'), 'creditconsent', ['company_id'], unique=False)
    op.create_index(op.f('ix_creditconsent_created_by_user_id'), 'creditconsent', ['created_by_user_id'], unique=False)
    op.create_index(op.f('ix_creditconsent_kind'), 'creditconsent', ['kind'], unique=False)
    op.create_index(op.f('ix_creditconsent_status'), 'creditconsent', ['status'], unique=False)
    op.create_table('creditreport',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.Column('created_by_user_id', sa.Integer(), nullable=False),
    sa.Column('provider', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('document_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('document_value', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('async_enabled', sa.Boolean(), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('http_status', sa.Integer(), nullable=False),
    sa.Column('message', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('consulta_uid', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('resultado_id', sa.Integer(), nullable=False),
    sa.Column('score', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('faixa_risco', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('risco_total_brl', sa.Float(), nullable=False),
    sa.Column('carteira_total_brl', sa.Float(), nullable=False),
    sa.Column('carteira_vencer_brl', sa.Float(), nullable=False),
    sa.Column('carteira_vencido_brl', sa.Float(), nullable=False),
    sa.Column('carteira_prejuizo_brl', sa.Float(), nullable=False),
    sa.Column('quantidade_instituicoes', sa.Integer(), nullable=False),
    sa.Column('quantidade_operacoes', sa.Integer(), nullable=False),
    sa.Column('obrigacao_assumida', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('obrigacao_resumida', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('potential_score', sa.Float(), nullable=False),
    sa.Column('potential_label', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('raw_json', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['client.id'], ),
    sa.ForeignKeyConstraint(['company_id'], ['company.id'], ),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_creditreport_client_id'), 'creditreport', ['client_id'], unique=False)
    op.create_index(op.f('ix_creditreport_company_id'), 'creditreport', ['company_id'], unique=False)
    op.create_index(op.f('ix_creditreport_consulta_uid'), 'creditreport', ['consulta_uid'], unique=False)
    op.create_index(op.f('ix_creditreport_created_by_user_id'), 'creditreport', ['created_by_user_id'], unique=False)
    op.create_index(op.f('ix_creditreport_document_type'), 'creditreport', ['document_type'], unique=False)
    op.create_index(op.f('ix_creditreport_document_value'), 'creditreport', ['document_value'], unique=False)
    op.create_index(op.f('ix_creditreport_potential_label'), 'creditreport', ['potential_label'], unique=False)
    op.create_index(op.f('ix_creditreport_provider'), 'creditreport', ['provider'], unique=False)
    op.create_index(op.f('ix_creditreport_status'), 'creditreport', ['status'], unique=False)
    op.add_column('attachment', sa.Column('credit_consent_id', sa.Integer(), nullable=True))
    op.add_column('attachment', sa.Column('credit_report_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_attachment_credit_consent_id'), 'attachment', ['credit_consent_id'], unique=False)
    op.create_index(op.f('ix_attachment_credit_report_id'), 'attachment', ['credit_report_id'], unique=False)
    op.create_foreign_key(None, 'attachment', 'creditconsent', ['credit_consent_id'], ['id'])
    op.create_foreign_key(None, 'attachment', 'creditreport', ['credit_report_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'attachment', type_='foreignkey')
    op.drop_constraint(None, 'attachment', type_='foreignkey')
    op.drop_index(op.f('ix_attachment_credit_report_id'), table_name='attachment')
    op.drop_index(op.f('ix_attachment_credit_consent_id'), table_name='attachment')
    op.drop_column('attachment', 'credit_report_id')
    op.drop_column('attachment', 'credit_consent_id')
    op.drop_index(op.f('ix_creditreport_status'), table_name='creditreport')
    op.drop_index(op.f('ix_creditreport_provider'), table_name='creditreport')
    op.drop_index(op.f('ix_creditreport_potential_label'), table_name='creditreport')
    op.drop_index(op.f('ix_creditreport_document_value'), table_name='creditreport')
    op.drop_index(op.f('ix_creditreport_document_type'), table_name='creditreport')
    op.drop_index(op.f('ix_creditreport_created_by_user_id'), table_name='creditreport')
    op.drop_index(op.f('ix_creditreport_consulta_uid'), table_name='creditreport')
    op.drop_index(op.f('ix_creditreport_company_id'), table_name='creditreport')
    op.drop_index(op.f('ix_creditreport_client_id'), table_name='creditreport')
    op.drop_table('creditreport')
    op.drop_index(op.f('ix_creditconsent_status'), table_name='creditconsent')
    op.drop_index(op.f('ix_creditconsent_kind'), table_name='creditconsent')
    op.drop_index(op.f('ix_creditconsent_created_by_user_id'), table_name='creditconsent')
    op.drop_index(op.f('ix_creditconsent_company_id'), table_name='creditconsent')
    op.drop_index(op.f('ix_creditconsent_client_id'), table_name='creditconsent')
    op.drop_table('creditconsent')
    # ### end Alembic commands ###
