"""tarefas anexos

Revision ID: d7356437b609
Revises: f2a7c3b8652c
Create Date: 2026-03-12 14:13:55.172668

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd7356437b609'
down_revision: Union[str, Sequence[str], None] = 'f2a7c3b8652c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('attachment', sa.Column('task_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_attachment_task_id'), 'attachment', ['task_id'], unique=False)
    op.create_foreign_key(None, 'attachment', 'task', ['task_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'attachment', type_='foreignkey')
    op.drop_index(op.f('ix_attachment_task_id'), table_name='attachment')
    op.drop_column('attachment', 'task_id')
    # ### end Alembic commands ###
