"""proposal service_name

Revision ID: e339241c223f
Revises: 9bfc4a077534
Create Date: 2026-03-11 20:57:05.330243

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'e339241c223f'
down_revision: Union[str, Sequence[str], None] = '9bfc4a077534'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('proposal', sa.Column('service_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.create_index(op.f('ix_proposal_service_name'), 'proposal', ['service_name'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_proposal_service_name'), table_name='proposal')
    op.drop_column('proposal', 'service_name')
    # ### end Alembic commands ###
