"""proposal service_name

Revision ID: f2a7c3b8652c
Revises: c865ab6fe5f5
Create Date: 2026-03-12 11:58:01.648763

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'f2a7c3b8652c'
down_revision: Union[str, Sequence[str], None] = 'c865ab6fe5f5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('task',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.Column('created_by_user_id', sa.Integer(), nullable=False),
    sa.Column('assignee_user_id', sa.Integer(), nullable=True),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('priority', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('due_date', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('visible_to_client', sa.Boolean(), nullable=False),
    sa.Column('client_action', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['assignee_user_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['client_id'], ['client.id'], ),
    sa.ForeignKeyConstraint(['company_id'], ['company.id'], ),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_task_assignee_user_id'), 'task', ['assignee_user_id'], unique=False)
    op.create_index(op.f('ix_task_client_action'), 'task', ['client_action'], unique=False)
    op.create_index(op.f('ix_task_client_id'), 'task', ['client_id'], unique=False)
    op.create_index(op.f('ix_task_company_id'), 'task', ['company_id'], unique=False)
    op.create_index(op.f('ix_task_created_by_user_id'), 'task', ['created_by_user_id'], unique=False)
    op.create_index(op.f('ix_task_priority'), 'task', ['priority'], unique=False)
    op.create_index(op.f('ix_task_status'), 'task', ['status'], unique=False)
    op.create_index(op.f('ix_task_visible_to_client'), 'task', ['visible_to_client'], unique=False)
    op.create_table('taskcomment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('task_id', sa.Integer(), nullable=False),
    sa.Column('author_user_id', sa.Integer(), nullable=False),
    sa.Column('message', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['author_user_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['task_id'], ['task.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_taskcomment_author_user_id'), 'taskcomment', ['author_user_id'], unique=False)
    op.create_index(op.f('ix_taskcomment_task_id'), 'taskcomment', ['task_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_taskcomment_task_id'), table_name='taskcomment')
    op.drop_index(op.f('ix_taskcomment_author_user_id'), table_name='taskcomment')
    op.drop_table('taskcomment')
    op.drop_index(op.f('ix_task_visible_to_client'), table_name='task')
    op.drop_index(op.f('ix_task_status'), table_name='task')
    op.drop_index(op.f('ix_task_priority'), table_name='task')
    op.drop_index(op.f('ix_task_created_by_user_id'), table_name='task')
    op.drop_index(op.f('ix_task_company_id'), table_name='task')
    op.drop_index(op.f('ix_task_client_id'), table_name='task')
    op.drop_index(op.f('ix_task_client_action'), table_name='task')
    op.drop_index(op.f('ix_task_assignee_user_id'), table_name='task')
    op.drop_table('task')
    # ### end Alembic commands ###
